
SPUMBRA_EXAMPLE_OUTPUT_FILES=$(call spumbra_make_output_files,$(SPUMBRA_EXAMPLE_SOURCE_FILES),$(SPUMBRA_EXAMPLES_DIRECTORY)/%,$(SPUMBRA_BUILD_DIRECTORY)/examples/%)
SPUMBRA_EXAMPLE_DEPENDENCY_FILES=$(call spumbra_make_dependency_files,$(SPUMBRA_EXAMPLE_SOURCE_FILES),$(SPUMBRA_EXAMPLES_DIRECTORY)/%,$(SPUMBRA_BUILD_DIRECTORY)/examples/%)