
#Alter the build directory based on the target, so as not to mix debug and release object files
SPUMBRA_TEST_DEBUG_TARGETS := sp-umbra/test/debug sp-umbra/test/debug/run
SPUMBRA_TEST_DEBUG_CLEAN_TARGETS:= sp-umbra/test/debug/clean

SPUMBRA_TEST_RELEASE_TARGETS := sp-umbra/test sp-umbra/test/release sp-umbra/test/run sp-umbra/test/release/run
SPUMBRA_TEST_RELEASE_CLEAN_TARGETS:= sp-umbra/test/clean sp-umbra/test/release/clean

SPUMBRA_TEST_DEBUG_MODES := $(filter $(SPUMBRA_TEST_DEBUG_TARGETS) $(SPUMBRA_TEST_DEBUG_CLEAN_TARGETS),$(MAKECMDGOALS))
SPUMBRA_TEST_RELEASE_MODES := $(filter $(SPUMBRA_TEST_RELEASE_TARGETS) $(SPUMBRA_TEST_RELEASE_CLEAN_TARGETS),$(MAKECMDGOALS))

ifneq ($(SPUMBRA_TEST_DEBUG_MODES),)
	SPUMBRA_BUILD_DIRECTORY := $(SPUMBRA_BUILD_DIRECTORY)/debug
	SPUMBRA_BINARY_DIRECTORY := $(SPUMBRA_BINARY_DIRECTORY)/debug
endif
ifneq ($(SPUMBRA_TEST_RELEASE_MODES),)
	SPUMBRA_BUILD_DIRECTORY := $(SPUMBRA_BUILD_DIRECTORY)/release
	SPUMBRA_BINARY_DIRECTORY := $(SPUMBRA_BINARY_DIRECTORY)/release
endif

SPUMBRA_TEST_OUTPUT_FILES=$(call spumbra_make_output_files,$(SPUMBRA_TEST_SOURCE_FILES),$(SPUMBRA_TEST_DIRECTORY)/%,$(SPUMBRA_BUILD_DIRECTORY)/test/%)
SPUMBRA_TEST_DEPENDENCY_FILES=$(call spumbra_make_dependency_files,$(SPUMBRA_TEST_SOURCE_FILES),$(SPUMBRA_TEST_DIRECTORY)/%,$(SPUMBRA_BUILD_DIRECTORY)/test/%)
SPUMBRA_TEST_DEPENDENCY_FILES+=$(SPUMBRA_TEST_MAIN_DEPENDENCY)

SPUMBRA_TEST_MAIN:=$(SPUMBRA_BUILD_DIRECTORY)/test/main.cpp.o
SPUMBRA_TEST_MAIN_DEPENDENCY:=$(SPUMBRA_BUILD_DIRECTORY)/test/main.cpp.d
SPUMBRA_TEST_APPLICATION:=$(SPUMBRA_BINARY_DIRECTORY)/sp-umbra-test 

SPUMBRA_SPUNIT_FORMATTING_FLAGS := --spunit-reporter=spec --spunit-stream-color=windows

sp-umbra/test: sp-umbra/test/release
sp-umbra/test/run: sp-umbra/test/release/run


sp-umbra/test/debug/run: sp-umbra/test/debug
	$(SPUMBRA_TEST_APPLICATION) $(SPUMBRA_SPUNIT_FORMATTING_FLAGS)

sp-umbra/test/debug: SPUMBRA_CPP_FLAGS += $(SPUMBRA_CPP_DEBUG_FLAGS) -DSPUMBRA_DEBUG -DSPUMBRA_TEST
sp-umbra/test/debug: $(SPUMBRA_TEST_APPLICATION)

sp-umbra/test/release/run: sp-umbra/test/release
	$(SPUMBRA_TEST_APPLICATION) $(SPUMBRA_SPUNIT_FORMATTING_FLAGS)

sp-umbra/test/release: SPUMBRA_CPP_FLAGS += $(SPUMBRA_CPP_RELEASE_FLAGS) -DSPUMBRA_RELEASE
sp-umbra/test/release: $(SPUMBRA_TEST_APPLICATION)

$(SPUMBRA_TEST_APPLICATION): SPUMBRA_CPP_FLAGS += -DSPUMBRA_TEST
$(SPUMBRA_TEST_APPLICATION): SPUMBRA_INCLUDE += -I$(SPUMBRA_SOURCE_DIRECTORY) -I$(SPUMBRA_TEST_DIRECTORY) -I$(SPUNIT_INCLUDE_DIRECTORY)
$(SPUMBRA_TEST_APPLICATION): $(SPUMBRA_TEST_OUTPUT_FILES) $(SPUMBRA_OUTPUT_FILES) $(SPUMBRA_TEST_MAIN) $(SPUNIT_LIBRARY)
	$(VERBOSE_FLAG)$(MAKE_DIRECTORY) $(@D)
	$(VERBOSE_FLAG)$(SPUMBRA_CPP) -o $@ $^

SPUMBRA_TEST_CLEAN_FILES := $(SPUMBRA_TEST_APPLICATION) \
							$(SPUMBRA_TEST_OUTPUT_FILES) \
							$(SPUMBRA_TEST_DEPENDENCY_FILES) \
							$(SPUMBRA_OUTPUT_FILES) \
							$(SPUMBRA_DEPENDENCY_FILES) \
							$(SPUMBRA_TEST_MAIN) \
							$(SPUMBRA_TEST_MAIN_DEPENDENCY)

sp-umbra/test/debug/clean:
	$(VERBOSE_FLAG)$(REMOVE_FILE) $(SPUMBRA_TEST_CLEAN_FILES)

sp-umbra/test/clean: sp-umbra/test/release/clean

sp-umbra/test/release/clean:
	$(VERBOSE_FLAG)$(REMOVE_FILE) $(SPUMBRA_TEST_CLEAN_FILES)