SPUNIT_BUILD_DIRECTORY = $(SPUMBRA_BUILD_DIRECTORY)/spunit
SPUNIT_BINARY_DIRECTORY = $(SPUMBRA_BINARY_DIRECTORY)
SPUNIT_LIBRARY = $(SPUMBRA_BINARY_DIRECTORY)/libspunit.a
#SPUNIT_DIR is the env variable
ifeq ($(SPUNIT_DIRECTORY),)
SPUNIT_DIRECTORY=$(SPUMBRA_DIRECTORY)../sp-unit
endif

SPUNIT_OVERRIDE_CPP=$(SPUMBRA_CPP)